name: bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bundler:
    name: Bundler ${{ matrix.bundler.name }} on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-20.04 }

        ruby:
          - { name: ruby-3.0, value: 3.0.3 }

        bundler:
          - { name: 2, value: '' }

    env:
      RGV: ..
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install graphviz (Ubuntu)
        run: sudo apt-get install graphviz -y
        if: matrix.bundler.value == '' && matrix.os.name == 'Ubuntu'
        working-directory: ./bundler
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/rake spec:realworld spec:sudo
        working-directory: ./bundler
    timeout-minutes: 60
