name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3
      - try_fix_file_locking_on_windows

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2019

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby-2.5, value: 2.5.9 }

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: bin/rspec spec/install/gems/resolving_spec.rb
        working-directory: ./bundler
        shell: bash
